
FROM debian:12

RUN apt-get update
RUN apt-get -y install python3 python3-pip libglib2.0-0 libgl1 libqt5gui5 libglu1-mesa diffutils python3-ezdxf python3-setproctitle python3-pyqt5 python3-numpy python3-opengl python3-pyqt5.qtopengl python3-freetype python3-pil python3-matplotlib

# for package building
RUN apt-get -y install python3-stdeb dh-python

#RUN pip3 install PyQt5 ezdxf PyOpenGL Pillow pygame pyclipper setproctitle freetype-py matplotlib svgwrite

CMD ["/bin/bash"]

