setup_defaults = {
    "workpiece": {
        "mirrorV": {
            "default": False,
            "type": "bool",
            "title": "Mirror-Vertical",
            "tooltip": "Flipping the Workpiece",
        },
        "mirrorH": {
            "default": False,
            "type": "bool",
            "title": "Mirror-Horizontal",
            "tooltip": "Flipping the Workpiece",
        },
        "rotate": {
            "default": "0",
            "type": "select",
            "options": (("0", "0"), ("1", "90"), ("2", "180"), ("3", "270")),
            "title": "Rotating",
            "tooltip": "Rotating the Workpiece",
        },
        "zero": {
            "default": "original",
            "type": "select",
            "options": (
                ("original", "original"),
                ("bottomLeft", "bottomLeft"),
                ("center", "center"),
                ("bottomRight", "bottomRight"),
                ("topLeft", "topLeft"),
                ("topRight", "topRight"),
            ),
            "title": "Zero-Position",
            "tooltip": "setting the Zero-Postition of the Workpiece",
        },
    },
    "tool": {
        "number": {
            "default": 1,
            "type": "int",
            "min": 1,
            "max": 99,
            "title": "Number",
            "tooltip": "setting the Tool-Number to load in gcode",
        },
        "diameter": {
            "default": 4.0,
            "type": "float",
            "min": 0.0,
            "max": 999.0,
            "title": "Diameter",
            "tooltip": "setting the Tool-Diameter to calculate the Offsets",
        },
        "speed": {
            "default": 10000,
            "type": "int",
            "min": 100,
            "max": 100000,
            "title": "Speed",
            "tooltip": "setting the Tool-Speed in RPM",
        },
    },
    "mill": {
        "rate_h": {
            "default": 1000,
            "type": "int",
            "min": 1,
            "max": 10000,
            "title": "Feed-Rate(Horizontal)",
            "tooltip": "the Horizotal Feetrate",
        },
        "rate_v": {
            "default": 100,
            "type": "int",
            "min": 1,
            "max": 10000,
            "title": "Feed-Rate(Vertical)",
            "tooltip": "the Vertical Feetrate",
        },
        "fast_move_z": {
            "default": 5.0,
            "type": "float",
            "min": 0.0,
            "max": 999.0,
            "title": "Fast-Move Z",
            "tooltip": "the Z-Position for fast moves",
        },
        "G64": {
            "default": 0.050000,
            "type": "float",
            "min": 0.0,
            "max": 0.1,
            "title": "G64-Value",
            "tooltip": "value for the G64 command",
        },
        "depth": {
            "default": -9.0,
            "type": "float",
            "min": -999.0,
            "max": 0.0,
            "per_object": True,
            "title": "Depth",
            "tooltip": "the end depth for milling",
        },
        "step": {
            "default": -9.0,
            "type": "float",
            "min": -999.0,
            "max": 0.0,
            "per_object": True,
            "title": "Step",
            "tooltip": "the maximum depth in one move",
        },
        "active": {
            "default": True,
            "type": "bool",
            "per_object": True,
            "title": "Active",
            "tooltip": "enable/disable this object",
        },
        "helix_mode": {
            "default": False,
            "type": "bool",
            "per_object": True,
            "title": "Helix-Mode",
            "tooltip": "",
        },
        "reverse": {
            "default": False,
            "type": "bool",
            "per_object": True,
            "title": "Reverse",
            "tooltip": "",
        },
        "pocket": {
            "default": False,
            "type": "bool",
            "per_object": True,
            "title": "Pocket",
            "tooltip": "do pocket operation on this object",
        },
        "back_home": {
            "default": True,
            "type": "bool",
            "title": "Back-Home",
            "tooltip": "move tool back to Zero-Possition after milling",
        },
        "small_circles": {
            "default": True,
            "type": "bool",
            "title": "Small-Circles",
            "tooltip": "milling small circles even if the tool is bigger",
        },
    },
    "view": {
        "path": {
            "default": "simple",
            "type": "select",
            "options": (
                ("minimal", "minimal"),
                ("simple", "simple"),
                ("full", "full"),
            ),
            "title": "Path",
            "tooltip": "how to show the gcode path in the 3d-View",
        },
    },
}
